version: '3'
services:
  app:
    image: event-publisher:latest
    restart: always
    build:
      context: ..
      dockerfile: ./build/event-publisher/Dockerfile
    volumes:
      - ../credentials:/app/credentials
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "credentials/credential.json"

  subscriber:
    image: event-subscriber:latest
    restart: always
    build:
      context: ..
      dockerfile: ./build/event-subscriber/Dockerfile
    volumes:
      - ../credentials:/app/credentials
    depends_on:
      - mongo
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "credentials/credential.json"

  mongo:
    image: mongo:4.4.14
    restart: always
    volumes:
      - ../scripts/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: event-poc

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:event-poc@mongo:27017/

  scheduler:
    image: event-scheduler:latest
    restart: always
    build:
      context: ..
      dockerfile: ./build/event-scheduler/Dockerfile
    volumes:
      - ../credentials:/app/credentials
    depends_on:
      - mongo
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "credentials/credential.json"
