version: '3'
services:
  app:
    image: event-publisher:latest
    restart: always
    build:
      context: ..
      dockerfile: ./build/event-publisher/Dockerfile
    volumes:
      - ../credentials:/app/credentials
      - ../configs:/app/configs
    depends_on:
      - fluentd
    ports:
      - "3000:3000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/credential.json"

  subscriber:
    image: event-subscriber:latest
    restart: always
    build:
      context: ..
      dockerfile: ./build/event-subscriber/Dockerfile
    volumes:
      - ../credentials:/app/credentials
      - ../configs:/app/configs
    depends_on:
      - fluentd
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/credential.json"

#  scheduler:
#    image: event-scheduler:latest
#    restart: always
#    build:
#      context: ..
#      dockerfile: ./build/event-scheduler/Dockerfile
#    volumes:
#      - ../credentials:/app/credentials
#      - ../configs:/app/configs
#    depends_on:
#      - fluentd
#    environment:
#      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/credential.json"

  fluentd:
    image: fluent/fluentd:v1.15.0-1.0
    volumes:
      - ./fluentd:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
