app:
  port: 3000
  baseRoute: "api"
  runMode: "debug"
  name: ""
  enableProfile: false

publisher:
  projectID: "media17-dev"
  topic: event-source

subscriber:
  projectID: "media17-dev"
  topic: event-source

mongo:
  host: mongo:27017
  scheme: mongodb
  username: root
  password: event-poc
  database: 17media
  poolSizeMultiplier: 1
  authDBName: admin